version: '3'

services:
  app:
    build: .
    container_name: mcp-dataforseo
    environment:
      - DATAFORSEO_USERNAME=${DATAFORSEO_USERNAME}
      - DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD}
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - default
      - coolify
    labels:
      - "traefik.enable=true"
      # Använd variabel för host-regel istället för hårdkodat värde
      - "traefik.http.routers.mcp-dataforseo.rule=Host(`${COOLIFY_FQDN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.mcp-dataforseo.entryPoints=http,https"
      - "traefik.http.services.mcp-dataforseo.loadbalancer.server.port=3003"
      # Lägg till middleware för gzip-komprimering
      - "traefik.http.middlewares.mcp-gzip.compress=true"
      - "traefik.http.routers.mcp-dataforseo.middlewares=mcp-gzip"

networks:
  coolify:
    external: true