version: '3'

services:
  app:
    build: .
    container_name: mcp-dataforseo
    environment:
      - DATAFORSEO_USERNAME=${DATAFORSEO_USERNAME}
      - DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD}
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - default
      - coolify
    labels:
      - "traefik.enable=true"
      # Använd variabel för host-regel istället för hårdkodat värde
      - "traefik.http.routers.mcp-dataforseo.rule=Host(`${COOLIFY_FQDN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.mcp-dataforseo.entryPoints=http,https"
      - "traefik.http.services.mcp-dataforseo.loadbalancer.server.port=3003"
      # Lägg till middleware för gzip-komprimering
      - "traefik.http.middlewares.mcp-gzip.compress=true"
      # Lägg till middleware för timeout-konfigurationer
      - "traefik.http.middlewares.mcp-timeout.forwardingTimeouts.idleTimeout=3600"
      - "traefik.http.middlewares.mcp-timeout.forwardingTimeouts.responseTimeout=3600"
      # Applicera både gzip och timeout middlewares
      - "traefik.http.routers.mcp-dataforseo.middlewares=mcp-gzip,mcp-timeout"
      # SSE-specifik konfiguration
      - "traefik.http.middlewares.mcp-sse-buffer.buffering.maxRequestBodyBytes=10485760"
      - "traefik.http.middlewares.mcp-sse-buffer.buffering.memResponseBodyBytes=2097152"

networks:
  coolify:
    external: true