version: '3'

services:
  app:
    build: .
    container_name: mcp-dataforseo
    environment:
      - DATAFORSEO_USERNAME=${DATAFORSEO_USERNAME}
      - DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD}
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - default
      - coolify
    labels:
      - "traefik.enable=true"
      # Förbättrad host-regel
      - "traefik.http.routers.mcp-dataforseo.rule=Host(`${COOLIFY_FQDN}`)"
      - "traefik.http.routers.mcp-dataforseo.entryPoints=http,https"
      - "traefik.http.services.mcp-dataforseo.loadbalancer.server.port=3003"
      
      # Timeout-konfigurationer för långvariga anslutningar
      - "traefik.http.middlewares.mcp-timeout.forwardingTimeouts.idleTimeout=3600"
      - "traefik.http.middlewares.mcp-timeout.forwardingTimeouts.responseTimeout=3600"
      
      # SSE-specifika headers
      - "traefik.http.middlewares.sse-headers.headers.customResponseHeaders.Cache-Control=no-cache,no-transform"
      - "traefik.http.middlewares.sse-headers.headers.customResponseHeaders.Connection=keep-alive"
      - "traefik.http.middlewares.sse-headers.headers.customResponseHeaders.X-Accel-Buffering=no"
      
      # Hälsokontrollkonfiguration för bättre tillgänglighet
      - "traefik.http.services.mcp-dataforseo.loadbalancer.healthCheck.path=/health"
      - "traefik.http.services.mcp-dataforseo.loadbalancer.healthCheck.interval=10s"
      - "traefik.http.services.mcp-dataforseo.loadbalancer.healthCheck.timeout=5s"
      
      # Kombinera alla middlewares
      - "traefik.http.routers.mcp-dataforseo.middlewares=mcp-timeout,sse-headers"

networks:
  coolify:
    external: true